console.log("============================================")
console.log("Hello form external script.")
console.log("============================================")
console.log("List of 10 foods:")
console.log("1.Cake")
console.log("2.Burger")
console.log("3.Pizza")
console.log("4.MO:MO")
console.log("5.Samosa")
console.log("6.Chicken Chilly")
console.log("7.Fried Rice")
console.log("8.Dal Bhat")
console.log("9.Biryani")
console.log("10.Sekwa")

alert("Hello welcome to my website")
// alert("Are you sure you want to quit!")
// alert("Do you want to delete it permanently?")
// alert("Your message successfully sent")
// alert("Are you sure you want to proceed?")
// alert("You are currently on the free plan.")
// alert("Your email address is invalid")
// alert("Something went worng")


// console.log(prompt("Enter your username:"))
// console.log(prompt("Enter your email:"))
// console.log(prompt("Enter your password:"))
// console.log(prompt("Enter your age:"))
// console.log(prompt("Enter your address:"))
// console.log(prompt("Enter your message:"))
// console.log(prompt("Enter your Father's Name"))
// console.log(prompt("Enter your Mother's Name"))

confirm("Are you sure you want to submit?")
confirm("Are you sure you want to buy this item?")
confirm("Are you sure you want to quit?")
confirm("Are you sure you want to cancel the payment?")
confirm("Are you sure you want to place this order?")
confirm("Are you sure you want to copy this page?")